apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-r630-pv
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: gitlab-r630-local
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /var/lib/zfs-pv/reliable/gitlab
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - r630-storage

