apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data
  namespace: gitlab
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: gitlab-r630-local
  volumeName: gitlab-r630-pv
  resources:
    requests:
      storage: 200Gi

